{{- if not .Values.existingAutoscalerSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "amqp-pod-autoscaler.fullname" . }}
  labels:
    app: amqp-pod-autoscaler
    chart: {{ template "amqp-pod-autoscaler.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if not .Values.existingRabbitSecret }}
  rabbitmq-username: {{ (toString .Values.amqp.username) | b64enc }}
  rabbitmq-password: {{ (toString .Values.amqp.password) | b64enc }}
  {{- end }}
  {{- if .Values.actian.im.clientId }}
  actian.im.client-id: {{ (toString .Values.actian.im.clientId) | b64enc }}
  {{- end }}
  {{- if .Values.actian.im.clientSecret }}
  actian.im.client-secret: {{ (toString .Values.actian.im.clientSecret) | b64enc }}
  {{- end }}
  {{- if .Values.actian.im.deviceCode }}
  actian.im.device-code: {{ (toString .Values.actian.im.deviceCode) | b64enc }}
  {{- end }}
  {{- if .Values.actian.im.userCode }}
  actian.im.user-code: {{ (toString .Values.actian.im.userCode) | b64enc }}
  {{- end }}
{{- end }}

